=== szrrizvi/rebacjavalibrary/trunk/src/main/resources/rebacPolicy.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema targetNamespace="http://www.example.org/rebac"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns="http://www.example.org/rebac">

	<xs:element name="policies">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="policy" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="policy">
		<xs:complexType>
			<xs:group ref= "variants"/>
		</xs:complexType>
	</xs:element>
	
	<xs:group name="variants">
		<xs:choice>						
			<xs:element name="true">
				<xs:complexType/>
			</xs:element>	
			<xs:element name="false">
				<xs:complexType/>
			</xs:element>
			<xs:element name="variable" type="typevar"/>	
			<xs:element name="and" type="typeandor"/>
			<xs:element name="or" type="typeandor"/>
			<xs:element name="not" type="typenot"/>
			<xs:element name="at" type="typeatbind"/>
			<xs:element name="bind" type="typeatbind"/>
			<xs:element name="box" type="typeboxdiamond"/>
			<xs:element name="diamond" type="typeboxdiamond"/>	
		</xs:choice>
	</xs:group>
	
	<xs:complexType name="typevar">
		<xs:simpleContent>
			<xs:extension base="xs:string">
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="typenot">
		<xs:group ref="variants"/>
	</xs:complexType>
	
	<xs:complexType name="typeandor">
		<xs:group ref="variants" maxOccurs="2" minOccurs="2"/>
	</xs:complexType>
	
	<xs:complexType name="typeatbind">
		<xs:sequence>
			<xs:element name="varID">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:group ref="variants"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeboxdiamond">
		<xs:sequence>
			<xs:element name="relId">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="direction" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="forward|backward|either"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:group ref="variants"/>
		</xs:sequence>
	</xs:complexType>
		
</xs:schema>

=== szrrizvi/rebacjavalibrary/trunk/src/test/resources/policyA.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:policy	xmlns:p="http://www.example.org/rebac" 
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			xsi:schemaLocation="http://www.example.org/rebac rebacPolicy.xsd ">
			
	<diamond>
		<relId direction="forward">1</relId>
		<diamond>
			<relId direction="forward">1</relId>
			<diamond>
				<relId direction="forward">1</relId>
				<requestor/>
			</diamond>
		</diamond>
	</diamond>
			
</p:policy>
